version: "3"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db"
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    
volumes:
  db:
